baseURL = "http://alexa-iot-workshop.s3-website-eu-west-1.amazonaws.com"
ignoreFiles = [ "\\.files/README.md$",  ]
languageCode = "en-us"
defaultContentLanguage = "en"
title = "AWS & Alexa Workshop"
theme = "hugo-theme-learn"
uglyurls = false
sectionPagesMenu = "main"
relativeURLs = true

[deployment]

[[deployment.targets]]
URL = "s3://alexa-iot-workshop?region=eu-west-1"

[blackfriday]
  hrefTargetBlank = true

[params]
editURL = "https://github.com/aws-samples/aws-alexa-workshop/edit/smarthome-en/content/"
themeVariant = "mine"
showVisitedLinks = false
author = "Massimiliano Angelino from Joe SHI work"
description = "AWS & Alexa Workshop"
disableSearch = false
disableAssetsBusting = false
disableShortcutsTitle = true
branch = "smarthome-en"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "tango"


[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/massi-ang/aws-alexa-workshop/tree/smarthome-en"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Have questions?"
url = "https://github.com/massi-ang/aws-alexa-workshop/issues"
weight = 40

[Languages]
[Languages.en]
title = "AWS & Alexa Workshop"
weight = 1
languageName = "English"

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]